# Generated by Django 4.2.15 on 2024-12-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0532_taxonomy_unique_on_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="cookieless_server_hash_mode",
            field=models.SmallIntegerField(choices=[(0, "Disabled"), (1, "Stateless"), (2, "Stateful")], default=0),
        ),
    ]
